default_context:
  project_name: 'myProject1'
  project_slug: 'myProject1'
  domain_main: 'myFirstProject'
  domain_staging: 'myFirstProject'
  docker_swarm_stack_name_main: 'myFirstProject'
  docker_swarm_stack_name_staging: 'myFirstProject'
  secret_key: '1d8baa665ca1677a57655c2adaad5cdf23ae3643162a88f1330fd616db846c4e'
  first_superuser: 'admin@myFirstProject'
  first_superuser_password: '1d8baa665ca1677a57655c2adaad5cdf23ae3643162a88f1330fd616db846c4e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.myFirstProject", "https://myFirstProject", "https://myFirstProject", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@myFirstProject'
  postgres_password: '08ea4fef401da859796185f7a3152ab3c0c6b0079010e4b952fe11a5160dbe91'
  pgadmin_default_user: 'admin@myFirstProject'
  pgadmin_default_user_password: '1d8baa665ca1677a57655c2adaad5cdf23ae3643162a88f1330fd616db846c4e'
  traefik_constraint_tag: 'myFirstProject'
  traefik_constraint_tag_staging: 'myFirstProject'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
